function [] = MakePattern_SpatFreq(freq,root,savePat)
%---------------------------------------------------------------------------------------------------------------------------------
% MakePattern_SpatFreq: makes pattern with two channels
% Channel-X: changes spatial frequency
% Channel-Y: rotates ground
%   INPUTS:
%       freq:       row vector containing spatial frequencies in degress
%       root:       directory to save file
%       savePat:    boolean (1 = save pattern)
%   OUTPUTS:
%---------------------------------------------------------------------------------------------------------------------------------
%   This program creates one structure ('pattern').  The relevant components of
%   this structure are as follows:
%
%       pattern  -  the parent structure
%               .x_num          -   xpos limits
%                                   by convention, xpos relates to translation and
%                                   rotations of a static pattern
%               .y_num          -   ypos limits
%                                   by convention, ypos relates to non-length
%                                   conserving transformations
%               .x_panels       -   number of panels in x direction
%               .y_panels       -   number of panels in y directions
%               .num_panels     -   number of panels in array
%                                   (.x_panels*.y_panels)
%               .panel_size     -   '0' gives default 8x8, '1' allows user specific
%               .gs_val         -   gray scale value (1-4)
%               .Pats           -   data for the panels...a 4D array where
%                                   (x_panels*x_size,y_panels*y_size,xpos,ypos)
%               .Panel_map      -   a 2x2 array specifying the location of the
%                                   named panels indexed from '1'
%               .BitMapIndex	-   output generated by executing
%                                   'process_panel_map(pattern);'
%               .data           -   output generated by executing
%                                   'make_pattern_vector(pattern);'
%---------------------------------------------------------------------------------------------------------------------------------
%% DEBUGGING %%
% ONLY UNCOMMENT & RUN THIS SECTION IF DEBUGGING %
%---------------------------------------------------------------------------------------------------------------------------------
% freq = 3.75*[2,4,6,8,12,16,24,32,48,96];
% root = 'Q:\Box Sync\Git\Arena\Patterns\';
% savePat = 1;
%% Set up panel variables %%
%---------------------------------------------------------------------------------------------------------------------------------
pattern.x_num = 96;                 % There are 96 pixel around the display (12x8) 
pattern.y_num = length(freq);       % # of spatial frequencies
pattern.num_panels = 48;            % This is the number of unique Panel IDs required
pattern.gs_val = 4;                 % This pattern will use 2 intensity levels
pattern.row_compression = 1;        % Columns are symmetric
pattern.x_panel = pattern.x_num;
pattern.y_panel = pattern.num_panels*8/pattern.x_num;
Int.High = 12; % high intensity value (0-15)
Int.Low = 4;  % low intensity value (0-15)
%% Make PATS %% d
%---------------------------------------------------------------------------------------------------------------------------------
% Calculate bar widths
barwidth = zeros(1,pattern.y_num);
for kk = 1:pattern.y_num
   barwidth(kk) = pattern.x_num*(freq(kk)/360);
end

% Check spatial frequencies
% goodFreq = barwidth(mod(pattern.x_num,barwidth)==0);
badFreq  = 3.75*barwidth(mod(pattern.x_num,barwidth)~=0);
if ~isempty(badFreq)
    err = '';
    for kk = 1:length(badFreq)
        err = [err,sprintf(['%1.1f' char(176) ' invalid \n'],badFreq(kk))];
    end
    err = [err,['Valid Frequencies are factors of 360' char(176) ' & divisible by 7.5']];
	error(err)
end

% Make y-channel spatial frequency
Pats = zeros(pattern.y_panel,pattern.x_panel,pattern.x_num,pattern.y_num);
qq = 1;
for jj = 1:pattern.y_num
    pp = 1;
    for kk = barwidth(jj):barwidth(jj):pattern.x_num
        Pats(:,pp:kk, 1, qq) = [Int.Low*ones(pattern.y_panel,barwidth(jj)/2) Int.High*ones(pattern.y_panel,barwidth(jj)/2)];
        pp = kk + 1;
    end
    qq = qq + 1;
end

% Make x-channel
for j = 1:pattern.y_num
    for i = 2:pattern.x_num
        Pats(:,:,i,j) = ShiftMatrix(Pats(:,:,i-1,j), 1, 'r', 'y'); 
    end
end

%% Save Pattern %%
%---------------------------------------------------------------------------------------------------------------------------------
if savePat
    pattern.Pats = Pats; % store pattern data
    pattern.Panel_map = [12 8 4 11 7 3 10 6 2  9 5 1;...  % store arena panel layout
                         24 20 16 23 19 15 22 18 14 21 17 13;...
                         36 32 28 35 31 27 34 30 26 33 29 25;...
                         48 44 40 47 43 39 46 42 38 45 41 37];
    pattern.BitMapIndex = process_panel_map(pattern);
    pattern.data = make_pattern_vector(pattern);
    
    % Name file
    strFreq = '';
    for kk = 1:length(freq)
       strFreq = [strFreq  num2str(freq(kk)) '_'];
    end
    strFreq = strtrim(strFreq);
	str = [root '\Pattern_SpatFreq_' strFreq '_Cont=' num2str(Int.High) '-' num2str(Int.Low) '_48Pan.mat'];
    
    save(str, 'pattern');
end
disp('DONE')
end

